spring.application.name=flightcrash

spring.datasource.url=jdbc:postgresql://localhost:5432/flightcrash
spring.datasource.username=flightcrash
spring.datasource.password=flightcrash

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
logging.level.org.hibernate.SQL=debug

spring.flyway.enabled=true

