# Render impose un port via la variable d'env PORT
server.port=${PORT:8080}

spring.application.name=flightcrash

# DB: fournie par Render via variables d'env
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Production
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Optionnel: réduire le bruit
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql=warn
